# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.0.1
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Python.Python.3.12
FileExtensions:
  - csv
  - tsv
Commands:
  - csvfab
Installers:
  - Architecture: neutral
    InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.0.1/csvfab-setup-1.0.1.exe
    InstallerSha256: 064E69C28C25A83476A8E8E140E99592D1F29AEA3D3DE7DBCC58D6ACCA12F874
ManifestType: installer
ManifestVersion: 1.6.0
