# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.0.1
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Python.Python.3.12
FileExtensions:
  - csv
  - tsv
Commands:
  - csvfab
Installers:
  - Architecture: neutral
    InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.0.1/csvfab-setup-1.0.1.exe
    InstallerSha256: 266E1943CE88F7E9C5D047371BC4929DABF1E8F94FE9B57BED3AA4FAB64D1D60
ManifestType: installer
ManifestVersion: 1.6.0
